const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(req,result,marketplaces,isAdmin){
  const f=result.filters, url=page=>'/ferramentas-ia/tabela-precos/base?'+new URLSearchParams({busca:f.search,marketplace:f.marketplace,duplicados:f.duplicates,pagina:page});
  const hidden=(name,value)=>`<input type="hidden" name="${name}" value="${esc(value)}">`;
  return `<style>
  .tpb-shell{max-width:none!important;min-width:0}.tpb-band{min-width:0}.tpb-filters{display:flex;gap:12px;align-items:end;flex-wrap:wrap;margin:18px 0}.tpb-filters label{display:grid;gap:6px;font-weight:700}.tpb-filters input,.tpb-filters select{box-sizing:border-box;width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:7px}.tpb-filters .tpb-search{flex:1;min-width:200px}.tpb-filters button{background:#009640!important;color:white!important;border:0!important;padding:11px 18px!important;border-radius:7px!important}.tpb-links{width:100%;table-layout:fixed;min-width:950px!important}.tpb-links th,.tpb-links td{text-align:left!important;padding:10px!important;white-space:normal!important;overflow-wrap:anywhere}.tpb-links col.market{width:115px}.tpb-links col.sku{width:105px}.tpb-links col.ad{width:210px}.tpb-links col.status{width:135px}.tpb-links col.action{width:145px}.tpb-links td:nth-child(4){line-height:1.4}.tpb-links .tpb-delete{background:#dc2626!important;color:#fff!important;border:1px solid #b91c1c!important;border-radius:7px!important;padding:9px 11px!important;white-space:nowrap!important;font-weight:800!important;cursor:pointer}.tpb-badge{display:inline-block;padding:5px 8px;border-radius:999px;background:#e2e8f0;font-size:12px;font-weight:800}.tpb-badge.duplicate{background:#fef3c7;color:#92400e}.tpb-pagination{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-top:16px}.tpb-pagination a{border:1px solid #bfd8c8;padding:8px 12px;border-radius:6px;color:#087334}.tpb-pagination input{width:65px;padding:7px}.tpb-pagination form{display:flex;gap:8px;align-items:center}
  </style><section class="tpb-band"><h2>Administrar vínculos</h2><p>Duplicado indica mais de um anúncio para o mesmo SKU no mesmo marketplace. A exclusão remove somente o vínculo do Plennatec; uma nova importação pode trazê-lo novamente.</p>
  <form method="get" class="tpb-filters"><label class="tpb-search">SKU ou número do anúncio<input name="busca" value="${esc(f.search)}" maxlength="120"></label><label>Marketplace<select name="marketplace"><option value="">Todos</option>${marketplaces.map(m=>`<option ${m===f.marketplace?'selected':''}>${esc(m)}</option>`).join('')}</select></label><label>Status<select name="duplicados"><option value="">Todos</option><option value="sim" ${f.duplicates==='sim'?'selected':''}>Duplicados</option><option value="nao" ${f.duplicates==='nao'?'selected':''}>Sem duplicidade</option></select></label><button>Filtrar vínculos</button><a href="/ferramentas-ia/tabela-precos/base">Limpar</a></form>
  <p>${result.total.toLocaleString('pt-BR')} vínculo(s) encontrados · Página ${result.page} de ${result.pages}</p><div class="tpb-scroll"><table class="tpb-links"><colgroup><col class="market"><col class="sku"><col class="ad"><col><col class="status">${isAdmin?'<col class="action">':''}</colgroup><thead><tr><th>Marketplace</th><th>SKU</th><th>Anúncio</th><th>Produto</th><th>Status</th>${isAdmin?'<th>Ação</th>':''}</tr></thead><tbody>${result.rows.map(l=>`<tr><td>${esc(l.marketplace)}</td><td><strong>${esc(l.sku)}</strong></td><td>${esc(l.id_loja)}</td><td style="white-space:normal!important;overflow-wrap:anywhere!important" title="${esc(l.nome)}">${esc(l.nome)}</td><td><span class="tpb-badge ${l.anuncios>1?'duplicate':''}">${l.anuncios>1?'Duplicado':'Único'}</span>${l.anuncios>1?`<small style="display:block;margin-top:5px">${l.anuncios} anúncios</small>`:''}</td>${isAdmin?`<td><form method="post" action="/ferramentas-ia/tabela-precos/vinculos/excluir" onsubmit="return confirm(this.dataset.confirmation)" data-confirmation="${esc('Excluir somente o vínculo do SKU '+l.sku+', anúncio '+(l.id_loja||'(sem número)')+' — '+l.marketplace+'? O produto e os outros anúncios serão preservados.')}">${hidden('csrf',req.session.linkDeleteCsrf)}${hidden('id',l.id)}${hidden('sku',l.sku)}${hidden('anuncio',l.id_loja)}${hidden('marketplace',l.marketplace)}${hidden('busca',f.search)}${hidden('filtro_marketplace',f.marketplace)}${hidden('duplicados',f.duplicates)}${hidden('pagina',result.page)}<button class="tpb-delete" style="background:#dc2626!important;color:#fff!important;border:1px solid #b91c1c!important;border-radius:7px!important;padding:9px 11px!important">Excluir vínculo</button></form></td>`:''}</tr>`).join('')||'<tr><td colspan="6">Nenhum vínculo encontrado.</td></tr>'}</tbody></table></div><div class="tpb-pagination">${result.page>1?`<a href="${esc(url(result.page-1))}">← Anterior</a>`:''}${result.page<result.pages?`<a href="${esc(url(result.page+1))}">Próxima →</a>`:''}<form method="get">${hidden('busca',f.search)}${hidden('marketplace',f.marketplace)}${hidden('duplicados',f.duplicates)}<label>Ir para página <input type="number" name="pagina" min="1" max="${result.pages}" value="${result.page}"></label><button>Ir</button></form><span>50 vínculos por página</span></div></section>`;
}
module.exports={render};
